# Arrow Pattern
symbol = ':'
print(" "*5 + symbol)
print(" "*4 + symbol*2)
print(" "*3 + symbol*3)
print(" "*2 + symbol*4)
print(" " + symbol*5)
print(" " + symbol*5)
print(" "*2 + symbol*4)
print(" "*3 + symbol*3)
print(" "*4 + symbol*2)
print(" "*5 + symbol)
print(" "*19 + symbol*1)
print(symbol*20)
print(" "*19 + symbol*1)
print(" "*5 + symbol)
print(" "*4 + symbol*2)
print(" "*3 + symbol*3)
print(" "*2 + symbol*4)
print(" " + symbol*5)
print(" " + symbol*5)
print(" "*2 + symbol*4)
print(" "*3 + symbol*3)
print(" "*4 + symbol*2)
print(" "*5 + symbol)
