# Diamond Arrow Pattern Program
print("     *")
print("    **")
print("   ***")
print("  ****")
print(" *************")
print("**************")
print(" *************")
print("  ****")
print("   ***")
print("    **")
print("     *")
